
options:
  project_name: 
    type: string
    description: "Name of the project to register the runner to (e.g. snapd)"
    default: "snapd"
  github_url:
    type: string
    description: "Full GitHub URL for the runner to register to (e.g. https://github.com/canonical/snapd)"
    default: "https://github.com/canonical/snapd/"
  registration_token:
    type: string
    description: "GitHub Actions registration token (short-lived). Provide via juju config."
    secret: true
  runner_count:
    type: int
    description: "How many LXD containers / runners to create"
    default: 5
  runner_name_prefix:
    type: string
    description: "Prefix used for created container names, (e.g. the env name like ps8)"
    default: "spread-agent"
  runner_labels:
    type: string
    description: "Comma separated labels to register for each runner"
    default: "spread-enabled"
  runner_http_proxy:
    type: string
    description: "HTTP proxy URL to use for the runners"
    default: ""
  runner_https_proxy:
    type: string
    description: "HTTPS proxy URL to use for the runners"
    default: ""
  runner_no_proxy:
    type: string
    description: "Comma separated list of hosts that should be excluded from proxying"
    default: ""
